### ISSUE TITLE
HGAM model setup questions

### ISSUE THREAD

**Issue by gcperk** [ninoxconsulting/birdtrends#2]
1. Best practice for defining the number of knots (assume we can have a no of years/ x?). is 5 years a good benchmark overall?
2. GAM - smoothing parameters (eg "tp" for thin plate regression spline, "cr" for cubic regression spline?)
3. stan model - number of chains - should this be parameterized?

**Comment by AdamCSmithCWS** [comment]
1. n_knots = floor(n_years_w_data/4)
2. tp seems to perform the best in our work with the GAMYE model, 
`smooth_basis <- mgcv::smoothCon(
        mgcv::s(years, k = n_knots + 1, bs = "tp"), data = data.frame(years),
        # drops constant and absorbs identifiability constraints into the basis
        absorb.cons = TRUE,
        # If TRUE, the smooth is reparameterized to turn the penalty into an
        # identity matrix, with the final diagonal elements zeroed
        # (corresponding to the penalty nullspace).
        diagonal.penalty = TRUE)`
3. I think we can allow the cmdstanr defaults to drive this (4 chains, run in parallel).

**Comment by gcperk** [comment]
Updated to set n_knots (years_data/4) for fit_hgam and fit_gam. 
Keep tp and default cmdstanr
